### ISSUE TITLE
盤上タップで進む/戻る

### ISSUE THREAD

**Issue by na2hiro** [na2hiro/Kifu-for-JS#11]
スマホでボタンを押しづらいため．
将棋ウォーズのようなイメージ
http://shogiwars.heroz.jp:3002/games/na2hiro-GoldPona-20130905_001354

**Comment by IshikawaSou** [comment]
将棋ウォーズも押しやすいかと言われると微妙ですが、他にいい方法も思いつかない感じですかね。
連盟ライブなどは、画面のだいたい右下左下で進む戻るだったけど。

**Comment by na2hiro** [comment]
モバイルフレンドリーなv5の一機能として実装。 #104

詳しくは https://kifu-for-js.81.la/blog/2023/09/01/kifu-for-js-v5
