### ISSUE TITLE
分岐有の棋譜が表示されません

### ISSUE THREAD

**Issue by latKatt** [na2hiro/Kifu-for-JS#16]
10手目以降から分岐が生じる棋譜の読み込みをしようとすると、「棋譜ファイルが壊れています： 0手目で失敗しました： cannot move opposite piece」というエラーがでて棋譜を表示できません。読み込めなかった棋譜は以下になります。以下の棋譜はkifu形式ですが、保存形式によらず10手目以降に分岐がある棋譜についてはエラーが発生しました。

\#KIF version=2.0 encoding=UTF-8
\# ---- Kifu for Windows V7 V7.11 棋譜ファイル ----
開始日時：2015/08/17 00:32:18
終了日時：2015/08/17 00:32:35
手合割：平手　　
先手：
後手：
手数----指手---------消費時間--
   1 ２六歩(27)   ( 0:01/00:00:01)
   2 ８四歩(83)   ( 0:01/00:00:01)
   3 ２五歩(26)   ( 0:01/00:00:02)
   4 ８五歩(84)   ( 0:00/00:00:01)
   5 ７八金(69)   ( 0:01/00:00:03)
   6 ３二金(41)   ( 0:01/00:00:02)
   7 ２四歩(25)   ( 0:01/00:00:04)
   8 同　歩(23)   ( 0:00/00:00:02)
   9 同　飛(28)   ( 0:01/00:00:05)
  10 ２三歩打     ( 0:05/00:00:07)+
  11 中断         ( 0:01/00:00:06)
まで10手で中断

変化：10手
  10 １四歩(13)   ( 0:01/00:00:03)
  11 中断         ( 0:01/00:00:06)
まで10手で中断

9手目以前から分岐する棋譜の場合は読み込めました。以下は読み込めた棋譜です。

\#KIF version=2.0 encoding=UTF-8
\# ---- Kifu for Windows V7 V7.11 棋譜ファイル ----
開始日時：2015/08/17 00:32:18
終了日時：2015/08/17 00:32:35
手合割：平手　　
先手：
後手：
手数----指手---------消費時間--
   1 ２六歩(27)   ( 0:01/00:00:01)
   2 ８四歩(83)   ( 0:01/00:00:01)
   3 ２五歩(26)   ( 0:01/00:00:02)
   4 ８五歩(84)   ( 0:00/00:00:01)
   5 ７八金(69)   ( 0:01/00:00:03)
   6 ３二金(41)   ( 0:01/00:00:02)
   7 ２四歩(25)   ( 0:01/00:00:04)
   8 同　歩(23)   ( 0:00/00:00:02)
   9 同　飛(28)   ( 0:01/00:00:05)+
  10 ２三歩打     ( 0:05/00:00:07)
  11 中断         ( 0:01/00:00:06)
まで10手で中断

変化：9手
   9 ２六飛(28)   ( 0:01/00:00:05)
  10 中断         ( 0:01/00:00:03)
まで9手で中断

**Comment by na2hiro** [comment]
ご報告ありがとうございます．
変化が二桁手数の時バグになることを確認しました．
json-kifu-formatのほうで対応します．

**Comment by na2hiro** [comment]
e93b3c3ab66d6428d99e62f8b9cfe52dc4fa34cf で対応しました．
