### ISSUE TITLE
詰将棋の.kifファイルが読み込めない

### ISSUE THREAD

**Issue by kikizake** [na2hiro/Kifu-for-JS#25]
現バージョンでは、詰将棋の.kifファイルが読み込めません。
サンプルの.kifでも読み込めないのでkifファイルの中身のフォーマットの問題ではありません。
仕方が無いので、.kifを.csaに変換すれば読み込めました。
是非、改善をお願いします。
それと、平手の棋譜でも「盤面反転」している状態で保存したものは読み込めません。
これは.kifファイルの中の「盤面反転」の行を削除すれば読み込めましたが、できればプログラム側でも対処してほしいと思います。

**Comment by na2hiro** [comment]
KIFに正式なフォーマットの定義がないため，実際にアプリケーションによって生成される棋譜を参考にそれを解釈するプログラムを書いています．

* 開けない棋譜ファイル
* それを生成したアプリケーションの名前

を教えていただけると助かります．よろしくお願いします．

P. S. こちらの9fu.kifは詰将棋(初期局面その他)ですがそれは読み込めますでしょうか． http://na2hiro.github.io/Kifu-for-JS/test/loadKif.html

**Comment by kikizake** [comment]
前回のメール内容の訂正および追加情報です。
9fu.kifの読み込みを再度トライすると読み込めました。
なお、動作環境は、Windows 7（64Bit）、IE11です。
こちらでの動作結果は以下です。

平手の.kif読み込み  OK
盤面が先手後手を反転表示した状態で保存した.kif読み込み NG
駒落の.kif読み込み OK
詰将棋 "9fu.kif"読み込み OK
詰将棋 その他の.kif読み込み NG
詰将棋 .csaf読み込み OK

.csaはNGだった.kifをcsaに変換したものです。
こちらでは、「柿木将棋 for iPad」、「Kifu for iPhone」、「Kifu for Windows（古いバージョン？）」、Windows版の「柿木将棋 8」を使用しています。
kifファイルのヘッダー部分は以下のようになっています。
--------------------------------------------------------------------------

■柿木将棋 for iPadで作成したファイルのヘッダー部
#KIF version=2.0 encoding=Shift_JIS
# ---- 柿木将棋 for iPad V2.30 棋譜ファイル ----
手合割：平手
後手の持駒：飛二 金四 銀三 桂二 香二 歩十六 
       ・
       ・
       ・
先手の持駒：香 
先手：詰方
後手：玉方
手数----指手---------消費時間--
&読み込み時表示
   1 ３一角成(53) ( 0:09/00:00:09)

■Windows版のソフト（Kifu for Windowsの古いバージョン？）で作成したファイル
# ----  柿木将棋(KIFUS) 棋譜ファイル (M2toK V1.41) ----
手合割：平手　　
後手の持駒：金四　銀四　桂二　香三　歩十八　
       ・
       ・
       ・
先手の持駒：角 桂 
先手：詰方
後手：玉方
手数----指手---------消費時間--
&読み込み時表示
   1 ４六角(35)   ( 0:06/00:00:06)

--------------------------------------------------------------------------
9fu.kifとの違いは、以下だと思います。
・開始終了日時がない。
・手合割が「その他」ではなく「平手」になっている。
・「&読み込み時表示」といった注釈が入っている。

おそらく、「&読み込み時表示」が平手の反転表示同様にNGなのだと思います。
よろしくお願いします。

**Comment by kikizake** [comment]
すみません。前回の投稿で.kifファイルの内容を貼り付けると一部の行が大きく文字修飾されるようです。
フォントが大きくボールドで表示された部分は、「#」の次が「半角スペース」で、その後「---- 柿木将棋 for iPad V2.30 棋譜ファイル ----」となっています。

さて、試しに新規に「Kifu for iPhone」で三手詰の配置、手順を作成してみました。
「Kifu for iPhone」では普通に再生できますが、「Kifu for JS」ではやはり再生できません。
ただし、.kifの内容を見ると「&読み込み時表示」といった行はありませんでした。
また、手番を示す行もありません。
以下に内容を全て貼り付けておきます。

#KIF version=2.0 encoding=Shift_JIS
# ---- Kifu for iPhone V3.21 棋譜ファイル ----
終了日時：2015/11/17 07:16:02
手合割：平手
後手の持駒：飛二 角 金四 銀 桂四 香四 歩十七 
  ９ ８ ７ ６ ５ ４ ３ ２ １
+---------------------------+
| ・ ・ ・v銀v玉v銀 ・ ・ ・|一
| ・ ・ ・ ・ ・ ・ ・ ・ ・|二
| ・ ・ ・ ・ と ・ ・ ・ ・|三
| ・ ・ ・ ・ ・ ・ 馬 ・ ・|四
| ・ ・ ・ ・ ・ ・ ・ ・ ・|五
| ・ ・ ・ ・ ・ ・ ・ ・ ・|六
| ・ ・ ・ ・ ・ ・ ・ ・ ・|七
| ・ ・ ・ ・ ・ ・ ・ ・ ・|八
| ・ ・ ・ ・ ・ ・ ・ ・ ・|九
+---------------------------+
先手の持駒：銀 
手数----指手---------消費時間--
   1 ５二馬(34)   ( 0:02/00:00:02)
   2 同　銀(61)   ( 0:01/00:00:01)
   3 ６二銀打     ( 0:01/00:00:03)
   4 詰み         ( 0:07/00:00:08)

どういうパターンがNGなのか正直分らなくなってきましたが、こちらでは詰将棋の.kifは全滅です。
よろしくお願いします。

**Comment by na2hiro** [comment]
すみません．時間が取れず，反応できていませんでした． http://github.com/na2hiro/json-kifu-format のほうで年末に対応します．

ちなみに盤面反転のほうのフォーマットは`&盤面反転`であっていますか？

**Comment by kikizake** [comment]
棋譜 for iPhoneでは以下のようになっています。
#KIF version=2.0 encoding=Shift_JIS
# ---- Kifu for iPhone V3.22 棋譜ファイル ----
盤面回転
開始日時：2015/12/21 18:42:02
終了日時：2015/12/21 18:42:18
手合割：平手
先手：先手
後手：後手
手数----指手---------消費時間--
   1 ７六歩(77)   ( 0:02/00:00:02)
   2 ８四歩(83)   ( 0:01/00:00:01)

よろしくお願いします。

**Comment by kikizake** [comment]
> http://github.com/na2hiro/json-kifu-format のほうで年末に対応します．
対応予定との事、ありがとうございます。
今は、詰将棋に限っては「Blunder.Converter」でCSAに変換して「Kifu for JS」に読み込ませています。
また、局面図は同様に棋譜データをSFENに変換してWebサービスを呼び出して画像を作成しています。
将来的な要望としては、SFENの読み込みにも対応して頂けると嬉しいです。

**Comment by na2hiro** [comment]
遅くなってすみません．検証と修正を開始しました．

* どうやらKifu for iPhoneでは他と違って持ち駒のスペースが半角であるためこけているとわかりました．半角も許すようにします．
* 盤面回転と読み込み時表示については，それに対応するJKFを用意していないため，ひとまず無視して読みこむようにします．

**Comment by na2hiro** [comment]
手合割がその他となっているべきところが平手というのもおかしいですね．バグ報告したほうがよさそうです．
ちなみにこちらのアプリでしょうか？ https://itunes.apple.com/jp/app/id302532668

**Comment by kikizake** [comment]
はい。そのアプリです。
柿木将棋 for iPadも使用しています。
よろしくお願いします。

**Comment by na2hiro** [comment]
可読性のため，勝手ながら棋譜を\`\`\`からなる行で囲ませていただきました．

**Comment by na2hiro** [comment]
遅ればせながら cc4e9d78e60a90fa9e443c6605099a43a0ed8bc3 にて対応し，添付の棋譜ファイルが読み込まれることを確認しました．

* "盤面回転" "&読み込み時表示" の含まれる棋譜に対応
* Kifu for iPhoneによるイレギュラーな棋譜(半角スペース区切り持ち駒，編集局面なのに"手合割：平手")に対応
  * これに関しては開発者の柿木さんに確認を依頼 https://twitter.com/ykakinoki/status/688260947870273536

また何かあったらよろしくお願いします．詳細なご報告ありがとうございました．
