### ISSUE TITLE
外部スクリプトを用いた棋譜更新対応

### ISSUE THREAD

**Issue by mizar** [na2hiro/Kifu-for-JS#27]
外部のスクリプトから更新棋譜データの流し込み、最新の局面の表示などの制御が出来るようにしたい。

以下のような2つの方向性は如何でしょうか。

- loadString呼び出しにおいて、既に生成した盤面の棋譜を更新したり、最新局面に遷移するかどうかを選択したりできるようにする。
- load呼び出しにおいて、ファイル名・URLの代わりに最新の棋譜文字列を返すfunctionオブジェクトも指定できるようにする。

**Comment by na2hiro** [comment]
ご提案ありがとうございます．確かに，拡張性のためにはそういったモデルに対する操作を外部に露出するということが必要ですね．自分自身でも，開発している別のプロジェクトをバックエンドとして接続する際にはこのままでは難しいと感じていました． https://github.com/na2hiro/Shogitter.hs/issues/4

箇条で挙げていただいたように実装しようと思います．

より良い形としては，現在loadで提供している「定期的に再読み込みをする」というものをプラグインとして外からくっつける形がありそうです．loadがない場合は自動更新間隔のドロップダウンも意味が無いので，UIと再読み込みのコントローラを一緒に挿入できるフレームワークを考えられればと思います．まあ，時間がかかるとよくないのでこれはfuture workになるかもしれませんが．

**Comment by mizar** [comment]
必ずしも先述の通りの実装で無くとも、盤面構築系(load,loadString)の返り値として、その盤面操作用のオブジェクトを返し、そこから各種情報の読み書き、更新系の操作などを行えるようにしても良いかもしれませんね。

**Comment by na2hiro** [comment]
とりあえず 7d5b72eb32139bc1af55ac6443949761f06d6d57 でコールバックを読み込めるように(`load`が`loadCallback`を使う例になっています)， e007c6ad6a0556d60b7aa78e72d3facca307871f でコントローラを返すようにしてみました．
より細かい操作については現状少し書きづらく，Reduxで書きなおしてからのほうが良さそうに感じました．

**Comment by mizar** [comment]
対応ありがとうございます。ひとまず [このようなお遊び](//jsfiddle.net/mizarjp/Lz1ob7vk/embedded/result,js,html/) ができるようになりました。
Reduxでの書き直しも期待しております。
