### ISSUE TITLE
.txtファイルの読み込み

### ISSUE THREAD

**Issue by Rest48** [na2hiro/Kifu-for-JS#31]
はじめまして。FC2ブログにて「四間飛車で最強になりたい」というブログを運用しているRest48 と申します。よろしくお願いします。
http://rest48shogi.blog.fc2.com/

当方が所持している .kif で、「Kifu-for-JS」で読めない棋譜がございましたので、ご報告いたします。
http://rest48shogi.web.fc2.com/20170223_2.kif

以下は要望です。
今まで「Kifu for Flash」を用いてブログ上に棋譜を表示しておりました。FC2 ブログでは .kif 形式のファイルはアップロードできませんが、「Kifu for Flash」は .txt でも読むことができるので、拡張子を .kif から .txt に変更してup することで対応していました。
このたび、貴殿が作成された「Kifu-for-JS」を用いてブログ上で表示したかったのですが、 .txt のファイルはスクリプト上で読むように記載しても読まないようです（なぜかWeb 上に表示されたソフトに .txt 形式のファイルをドラッグ＆ドロップすると読めるようですが）。
以下の通りに記載しています。なお、FC2 ブログでは改行すると勝手に<br>を挿入して走らなくなるので、改行はなくしてあります。

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script><script src="http://blog-imgs-97.fc2.com/r/e/s/rest48shogi/kifuforjs.js" charset="utf-8"></script><script>var Kifu = require("Kifu");Kifu.settings={ImageDirectoryPath: "http://blog-imgs-97.fc2.com/r/e/s/rest48shogi"};</script><link rel="stylesheet" type="text/css" href="http://blog-imgs-97.fc2.com/r/e/s/rest48shogi/kifuforjs.css"><script>Kifu.load("http://rest48shogi.web.fc2.com/20170224.kif");</script>

大変お手数ですが、もしよろしければ .txt 形式でも読めるようにできないでしょうか？ご検討よろしくお願いいたします。

**Comment by na2hiro** [comment]
返事が遅くなってすみません．確認してご返答します．

**Comment by na2hiro** [comment]
フォーマットの調査に関しては https://github.com/na2hiro/json-kifu-format/issues/31 で行い，このissueでは.txtファイルの読み込みを趣旨にします．
