### ISSUE TITLE
持駒の歩が2-3枚ある場合の表示不具合

### ISSUE THREAD

**Issue by mizar** [na2hiro/Kifu-for-JS#34]
http://wdoor.c.u-tokyo.ac.jp/shogi/LATEST/2017/06/21/wdoor+floodgate-300-10F+gpsfish_normal_1c+yrz7_Cortex-A53_1c+20170621213011.csa

上記棋譜において、
20手目：後手の持駒が「歩２」→「角歩２」なのに表示が「角歩」
29手目：先手の持駒が「飛金桂歩３」、歩の表示が縦にはみ出す
などの不具合があるように見受けられます。

持駒の歩の枚数が2-3枚の場合は縦に並べる、という部分が混乱の元になっているように見受けられるので、このような場合にも歩は横に並べるようにしては如何でしょうか。

**Comment by mizar** [comment]
https://github.com/orangain/Kifu-for-JS/commit/9c32d07a66e800be50736960a5d419899c77d9dd にて、この問題の回避は可能であるようです。

**Comment by orangain** [comment]
#33 をマージいただいたので、この問題のPR出しておきます。

**Comment by na2hiro** [comment]
@mizar ご報告ありがとうございました．どうも最近の変更で入ったバグのようですね．
@orangain 迅速にPRを作っていただきありがとうございました．
