### ISSUE TITLE
分岐が多いKIFが部分的に表示されません

### ISSUE THREAD

**Issue by l33q** [na2hiro/Kifu-for-JS#36]
お邪魔します。
KIFファイルの一箇所に３つ以上の分岐があると、最初の２つまでしか表示されないようです。
例えば、
   1 ７六歩(77)   ( 0:00/00:00:00)+

変化：1手
   1 ２六歩(27)   ( 0:00/00:00:00)+

変化：1手
   1 ７八金(69)   ( 0:00/00:00:00)
みたいなKIFですと、７八金の分岐が見えません。
サンプルコードの henka.kif で何とぞご確認をお願いいたします。

**Comment by l33q** [comment]
自分でデバッグ入れて調べてみました。
不具合の原因は
node_modules/json-kifu-format/lib/kif-parser.js
の72行目にあると思われます。
        		while(fork.te>nowFork.te){fork = forkStack.pop();}
を
        		while(fork.te>=nowFork.te){fork = forkStack.pop();}
に直すと、私の観察する限りでは不具合が解消されます。
もしこの修正が正しければ、取り入れていただければ幸いです。

**Comment by na2hiro** [comment]
返答が遅くなってしまい申し訳ないです．
確かに，3つ以上の分岐にバグがあるようですね．
原因まで調べていただいてありがとうございます．
そのうち修正します．

**Comment by na2hiro** [comment]
まさに仰る通りの修正で間違いありませんでした．

https://github.com/na2hiro/json-kifu-format/commit/95c2c0f0d4c9b6811d35b7e055d92a6a3492de24 の変更を含む`json-kifu-format 1.1.1`および`kifu-for-js 1.2.1`をpublishしました．
どうもありがとうございました．
