### ISSUE TITLE
変化の変化が「同　」で始まる場合にエラー？

### ISSUE THREAD

**Issue by l33q** [na2hiro/Kifu-for-JS#37]
#36 ではご対応ありがとうございました。
実はもう一つ、エラーになってしまう KIF データがあります。
下記は Kifu for Windows で作った棋譜です。

[doh_branch.txt](https://github.com/na2hiro/Kifu-for-JS/files/1349501/doh_branch.txt)

これが現行の json-kifu-format 1.1.1 + kifu-for-js 1.2.1 では「棋譜形式エラー」になってしまいます。
ファイルを編集して「同　飛」を「２二飛」に書き換えると正常になります。(回避策にはなりますが、一時凌ぎに過ぎません。)
どうやら**変化手順の変化手順**が「同　」の手で始まると、エラーになる場合があるようですが、不具合の発生する正確な条件はわかりません。

**Comment by na2hiro** [comment]
ご報告ありがとうございます．
分岐の1手目が"同"の場合，怪しそうですね．調べてみます．

**Comment by na2hiro** [comment]
遅くなってしまいすみません．

https://github.com/na2hiro/json-kifu-format/commit/97c9e317992501976e781ac3ad90279dd1bbae72 で修正しました．次回のKifu for JSで取り込みます．

**Comment by na2hiro** [comment]
リリースされました． https://github.com/na2hiro/Kifu-for-JS/releases/tag/v2.0.0
