### ISSUE TITLE
棋譜形式エラーについて

### ISSUE THREAD

**Issue by hirotsumeshogi** [na2hiro/Kifu-for-JS#43]
初めまして。
FC2ブログにて「詰将棋の欠片」というブログを運営しております、hirotsumeshogiと申します。

現在、ブログに掲載している詰将棋のKifu for JS化を進めております。
ki2ファイルをtxtファイルに変換しFC2ホームページにアップロード、htmlファイルにてKifu.load関数による読み込みを行っております。

この度、「棋譜形式エラー」が発生いたしました。
ファイル名の変更等を試みましたが、エラーは解消できておりません。
下記に対象ファイルを配置いたしましたので、お手数ですが、ご調査の程よろしくお願いいたします。

https://hirotsume.web.fc2.com/kobayashi_kinsho196702.txt
https://hirotsume.web.fc2.com/kobayashi_kinsho196702.html

それでは、失礼いたします。

**Comment by na2hiro** [comment]
対応がとても遅くなって申し訳ありません。馬"左"というところでどちらの馬が動くかというロジックに誤りがあり、修正しました。こちらのバージョンで修正済みです。 https://github.com/na2hiro/Kifu-for-JS/releases/tag/v2.1.6
