### ISSUE TITLE
封じ手への対応

### ISSUE THREAD

**Issue by deiectus** [na2hiro/Kifu-for-JS#44]
初めまして

いつも愛用させてもらっています。

本日、王位戦をブックマークレットで観戦しようとしたところ棋譜形式エラーがでました。
エラーメッセージからおそらく封じ手に対応できていないんだろうと思われます。

お手数ですが、ご調査の程よろしくお願いいたします。

元の形式のまま棋譜からコメントを削除して貼り付ける方法がわからないので、
封じ手の部分だけ下記に記します

``50 封じ手       (33:00/04:12:00)
まで49手で封じ手``

**Comment by na2hiro** [comment]
返事が遅くなってすみません。

2020年頃にKIFでは「中断」として解釈するよう仮対応していたようで、今日KI2も同様にしてこのあと反映予定です。なお中断としているのは、JKF形式は今のところ[CSA形式](http://www2.computer-shogi.org/protocol/record_v22.html)の「特殊な指し手、終局状況」に則っている内部的な事情のためです。今後 #91 など形式の拡張をしてから表示も「封じ手」にできるはずです。
