### ISSUE TITLE
CSA形式: komabetsuline の中身が空だと読み込めない

### ISSUE THREAD

**Issue by mizar** [na2hiro/Kifu-for-JS#50]
see: https://github.com/na2hiro/json-kifu-format/issues/52

**Comment by na2hiro** [comment]
[`3.0.2`](https://github.com/na2hiro/Kifu-for-JS/releases/tag/v3.0.2) をpublishしました。 (ファイル内のバージョンが3.0.1になっていますがバグです、今度直します https://github.com/na2hiro/Kifu-for-JS/issues/57)
